Implement dot product and try adding test
Vyxal/Myxal pull request #2
Opened 2022-05-29 16:39 UTC by cgccuser

Implemented dot product, but I can't get tests to run with `./gradlew :runtime:test`. Output is
```
> Task :runtime:compileTestKotlin FAILED
'compileTestJava' task (current target is 11) and 'compileTestKotlin' task (current target is 1.8) jvm target compatibility should be set to the same Java version.
e: /workspace/Myxal/runtime/src/test/kotlin/io/github/seggan/myxal/TestHelper.kt: (3, 31): Unresolved reference: Main
e: /workspace/Myxal/runtime/src/test/kotlin/io/github/seggan/myxal/TestHelper.kt: (16, 9): Unresolved reference: doMain
```

Any idea how to fix it?

2022-05-30 18:24 UTC, Seggan requested changes

2022-05-30 18:24 UTC, Seggan commented on compiler/src/main/kotlin/io/github/seggan/myxal/compiler/jvm/JvmCompiler.kt
> +// import io.github.seggan.myxal.compiler.jvm.msplit.SplitMethod
Can remove this comment

2022-05-30 18:24 UTC, Seggan commented on compiler/src/main/kotlin/io/github/seggan/myxal/compiler/jvm/wrappers/MyxalMethod.kt
> +// import io.github.seggan.myxal.compiler.jvm.msplit.SplitMethod
Same here

2022-05-30 18:24 UTC, Seggan commented on runtime/src/main/kotlin/io/github/seggan/myxal/runtime/RuntimeMethods.kt
> +    val rhs = stack.pop()
Please use `a` and `b` for consistency

2022-05-30 18:24 UTC, Seggan commented on runtime/src/test/kotlin/io/github/seggan/myxal/runtime/ListTests.kt
> +                                )
```suggestion
                                ).jyxal()
```

2022-05-30 18:25 UTC, cgccuser commented
@Seggan I made PR 2 before #4, so it hasn't caught up yet. I'll fix that stuff once #4 is merged.

2022-06-02 23:35 UTC, cgccuser commented
Look at #5 instead

2022-06-02 23:35 UTC, closed without merging